# -*- coding: utf-8 -*-
"""path finding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1onLhVcSDBgiWrWPZqeVv1LinxUWpqKd9
"""

import heapq
import logging
from typing import List, Optional, Tuple

import numpy as np


logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)


# --- 1. ENVIRONMENT MAPPING ---

def create_occupancy_grid(
    grid_width: int,
    grid_height: int,
    obstacles: List[Tuple[int, int]]
) -> np.ndarray:
    """
    Create a 2D occupancy grid representing the drone's environment.

    0 = Free space
    1 = Obstacle

    The obstacle coordinates can represent objects identified by a
    computer vision pipeline, such as buildings, trees, or restricted zones.
    """
    grid = np.zeros((grid_height, grid_width), dtype=int)

    for obs_x, obs_y in obstacles:
        if 0 <= obs_x < grid_width and 0 <= obs_y < grid_height:
            grid[obs_y][obs_x] = 1

    return grid


# --- 2. PATHFINDING ALGORITHM (A*) ---

class Node:
    """Represents a position evaluated by the A* algorithm."""

    def __init__(
        self,
        position: Tuple[int, int],
        parent: Optional["Node"] = None
    ):
        self.position = position
        self.parent = parent

        # Cost from start node
        self.g = 0.0

        # Estimated cost from current node to goal
        self.h = 0.0

        # Total estimated cost
        self.f = 0.0

    def __eq__(self, other):
        if not isinstance(other, Node):
            return NotImplemented
        return self.position == other.position

    def __lt__(self, other):
        return self.f < other.f


def get_heuristic(
    current: Tuple[int, int],
    goal: Tuple[int, int]
) -> float:
    """
    Calculate the octile distance between two points.

    Octile distance is suitable for 8-directional movement where
    straight movement costs 1.0 and diagonal movement costs sqrt(2).
    """
    dx = abs(current[0] - goal[0])
    dy = abs(current[1] - goal[1])

    diagonal_cost = 1.414

    return (
        max(dx, dy)
        + (diagonal_cost - 1.0) * min(dx, dy)
    )


def is_valid_position(
    grid: np.ndarray,
    position: Tuple[int, int]
) -> bool:
    """Check whether a position is inside the navigation grid."""
    x, y = position

    return (
        0 <= x < grid.shape[1]
        and 0 <= y < grid.shape[0]
    )


def find_shortest_path(
    grid: np.ndarray,
    start: Tuple[int, int],
    goal: Tuple[int, int]
) -> Optional[List[Tuple[int, int]]]:
    """
    Use the A* algorithm to find a shortest path from start to goal.

    The drone can move in 8 directions:
    - Up
    - Down
    - Left
    - Right
    - Four diagonal directions

    Returns:
        A list of coordinates representing the calculated route,
        or None if the goal cannot be reached.
    """

    # Validate start and goal positions
    if not is_valid_position(grid, start):
        logger.error("Start position is outside the grid.")
        return None

    if not is_valid_position(grid, goal):
        logger.error("Goal position is outside the grid.")
        return None

    # Check whether start or goal is occupied
    if grid[start[1]][start[0]] == 1:
        logger.error("Start position is blocked by an obstacle.")
        return None

    if grid[goal[1]][goal[0]] == 1:
        logger.error("Goal position is blocked by an obstacle.")
        return None

    open_list = []
    closed_set = set()

    start_node = Node(start)
    goal_node = Node(goal)

    # Start node has f = g + h
    start_node.h = get_heuristic(start, goal)
    start_node.f = start_node.g + start_node.h

    heapq.heappush(open_list, (start_node.f, start_node))

    # 8 possible movement directions
    movements = [
        (0, -1),    # Up
        (0, 1),     # Down
        (-1, 0),    # Left
        (1, 0),     # Right
        (-1, -1),   # Up-left
        (-1, 1),    # Down-left
        (1, -1),    # Up-right
        (1, 1)      # Down-right
    ]

    while open_list:
        current_node = heapq.heappop(open_list)[1]

        if current_node.position in closed_set:
            continue

        closed_set.add(current_node.position)

        # Goal reached
        if current_node == goal_node:
            path = []
            current = current_node

            while current is not None:
                path.append(current.position)
                current = current.parent

            logger.info("Path found successfully.")
            return path[::-1]

        # Evaluate neighboring positions
        for move in movements:

            node_position = (
                current_node.position[0] + move[0],
                current_node.position[1] + move[1]
            )

            # Check grid boundaries
            if not is_valid_position(grid, node_position):
                continue

            # Check whether the destination is blocked
            if grid[node_position[1]][node_position[0]] == 1:
                continue

            # Prevent diagonal corner cutting.
            # The drone cannot move diagonally between two blocked cells.
            if move[0] != 0 and move[1] != 0:

                horizontal_position = (
                    current_node.position[0] + move[0],
                    current_node.position[1]
                )

                vertical_position = (
                    current_node.position[0],
                    current_node.position[1] + move[1]
                )

                if (
                    grid[
                        horizontal_position[1]
                    ][horizontal_position[0]] == 1
                    or
                    grid[
                        vertical_position[1]
                    ][vertical_position[0]] == 1
                ):
                    continue

            # Skip positions already evaluated
            if node_position in closed_set:
                continue

            neighbor = Node(
                node_position,
                current_node
            )

            # Straight movement = 1.0
            # Diagonal movement = sqrt(2) ≈ 1.414
            if move[0] != 0 and move[1] != 0:
                movement_cost = 1.414
            else:
                movement_cost = 1.0

            neighbor.g = (
                current_node.g + movement_cost
            )

            neighbor.h = get_heuristic(
                neighbor.position,
                goal_node.position
            )

            neighbor.f = neighbor.g + neighbor.h

            # Check whether a better route to this position
            # already exists in the open list.
            better_route_exists = any(
                open_node.position == neighbor.position
                and open_node.g <= neighbor.g
                for _, open_node in open_list
            )

            if better_route_exists:
                continue

            heapq.heappush(
                open_list,
                (neighbor.f, neighbor)
            )

    logger.warning(
        "No valid path found. Goal is unreachable."
    )

    return None


# --- 3. VISUALIZATION ---

def visualize_grid(
    grid: np.ndarray,
    path: Optional[List[Tuple[int, int]]],
    start: Tuple[int, int],
    goal: Tuple[int, int]
) -> None:
    """
    Print an ASCII representation of the environment,
    obstacles, start/goal positions, and calculated route.

    Legend:
        S = Start
        G = Goal
        # = Obstacle
        * = Calculated path
        . = Free space
    """

    height, width = grid.shape
    path_set = set(path) if path else set()

    print("\n--- Drone Flight Path Simulation ---")
    print("Legend: S=Start, G=Goal, #=Obstacle, *=Path, .=Free Space\n")

    for y in range(height):
        row_string = ""

        for x in range(width):

            current_position = (x, y)

            if current_position == start:
                row_string += "S "

            elif current_position == goal:
                row_string += "G "

            elif current_position in path_set:
                row_string += "* "

            elif grid[y][x] == 1:
                row_string += "# "

            else:
                row_string += ". "

        print(row_string)

    print("------------------------------------\n")


# --- 4. DEMONSTRATION ---

if __name__ == "__main__":

    # Define a 10 x 10 navigation map
    MAP_WIDTH = 10
    MAP_HEIGHT = 10

    # Define drone start and destination coordinates
    drone_start = (0, 0)
    target_destination = (9, 9)

    # Example obstacles representing objects detected
    # by a computer vision pipeline.
    detected_obstacles = [
        (3, 0),
        (3, 1),
        (3, 2),
        (3, 3),
        (3, 4),

        (7, 5),
        (7, 6),
        (7, 7),
        (7, 8),
        (7, 9)
    ]

    # Generate the navigation grid
    logger.info("Generating environment grid...")

    environment_grid = create_occupancy_grid(
        MAP_WIDTH,
        MAP_HEIGHT,
        detected_obstacles
    )

    # Calculate the route
    logger.info("Calculating optimal path...")

    route = find_shortest_path(
        environment_grid,
        drone_start,
        target_destination
    )

    # Display the result
    if route:

        logger.info("Path found successfully.")

        visualize_grid(
            environment_grid,
            route,
            drone_start,
            target_destination
        )

        print(
            f"Total waypoints in route: {len(route)}"
        )

        print(
            f"Coordinate list: {route}"
        )

    else:

        logger.warning(
            "Unable to calculate a valid route."
        )