# -*- coding: utf-8 -*-
"""PPE and helmet detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_vh29ZzizvRKRfgYwE-Bm_j3TXtGfUUw
"""

import cv2

import numpy as np

from pathlib import Path

from typing import List, Dict, Tuple, Optional

from ultralytics import YOLO

import logging

logging.basicConfig(level=logging.INFO)

logger = logging.getLogger(__name__)

def detect_single_image(image_path: str, model_path: str, conf_threshold: float = 0.5) -> Dict:

model = YOLO(model_path)

results = model.predict(

source=image_path,

conf=conf_threshold,

verbose=False

)

result = results[0]

detections = {

'image_path': image_path,

'image_shape': result.orig_shape,

'detections': []

}

boxes = result.boxes

for box in boxes:

x1, y1, x2, y2 = box.xyxy[0].tolist()

x1_norm, y1_norm, x2_norm, y2_norm = box.xyxyn[0].tolist()

class_id = int(box.cls[0].item())

class_name = result.names[class_id]

confidence = box.conf[0].item()

width = x2 - x1

height = y2 - y1

area = width * height

detection_data = {

'class_id': class_id,

'class_name': class_name,

'confidence': round(confidence, 3),

'bbox_xyxy': {

'x1': int(x1),

'y1': int(y1),

'x2': int(x2),

'y2': int(y2)

},

'bbox_normalized': {

'x1_norm': round(x1_norm, 4),

'y1_norm': round(y1_norm, 4),

'x2_norm': round(x2_norm, 4),

'y2_norm': round(y2_norm, 4)

},

'dimensions': {

'width': int(width),

'height': int(height),

'area': int(area)

}

}

detections['detections'].append(detection_data)

logger.info(f"Detected {len(detections['detections'])} objects in {image_path}")

return detections

def draw_detections(image_path: str, model_path: str, output_path: str, conf_threshold: float = 0.5) -> None:

model = YOLO(model_path)

results = model.predict(

source=image_path,

conf=conf_threshold,

verbose=False

)

result = results[0]

annotated_image = result.plot()

cv2.imwrite(output_path, annotated_image)

logger.info(f"Annotated image saved to {output_path}")

def detect_batch_images(image_folder: str, model_path: str, conf_threshold: float = 0.5) -> List[Dict]:

model = YOLO(model_path)

image_extensions = {'.jpg', '.jpeg', '.png', '.bmp', '.tiff'}

image_paths = [

str(p) for p in Path(image_folder).rglob('*')

if p.suffix.lower() in image_extensions

]

logger.info(f"Processing {len(image_paths)} images from {image_folder}")

all_detections = []

for image_path in image_paths:

detections = detect_single_image(image_path, model_path, conf_threshold)

all_detections.append(detections)

return all_detections

def detect_video(video_path: str, model_path: str, output_path: str, conf_threshold: float = 0.5) -> None:

model = YOLO(model_path)

cap = cv2.VideoCapture(video_path)

fps = int(cap.get(cv2.CAP_PROP_FPS))

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))

height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

fourcc = cv2.VideoWriter_fourcc(*'mp4v')

out = cv2.VideoWriter(output_path, fourcc, fps, (width, height))

frame_count = 0

while True:

ret, frame = cap.read()

if not ret:

break

frame_count += 1

results = model.predict(source=frame, conf=conf_threshold, verbose=False)

result = results[0]

annotated_frame = result.plot()

out.write(annotated_frame)

if frame_count % 30 == 0:

logger.info(f"Processed {frame_count}/{total_frames} frames")

cap.release()

out.release()

logger.info(f"Video processing complete. Output saved to {output_path}")

def filter_detections_by_class(detections: Dict, target_classes: List[str]) -> Dict:

filtered = detections.copy()

filtered['detections'] = [

det for det in detections['detections']

if det['class_name'] in target_classes

]

logger.info(f"Filtered to {len(filtered['detections'])} detections from {len(detections['detections'])} total")

return filtered

def check_ppe_compliance(detections: Dict, ppe_classes: Dict[str, str]) -> Dict:

workers = [d for d in detections['detections'] if d['class_name'] == 'worker']

ppe_items = [d for d in detections['detections'] if d['class_name'] in ppe_classes.get('worker', [])]

compliance_analysis = {

'image_path': detections['image_path'],

'total_workers': len(workers),

'total_ppe_items': len(ppe_items),

'workers_with_ppe': 0,

'workers_without_ppe': 0,

'non_compliant_workers': []

}

for worker in workers:

wx1, wy1 = worker['bbox_xyxy']['x1'], worker['bbox_xyxy']['y1']

wx2, wy2 = worker['bbox_xyxy']['x2'], worker['bbox_xyxy']['y2']

worker_region = {

'x1': wx1, 'y1': wy1, 'x2': wx2, 'y2': wy2,

'center_x': (wx1 + wx2) // 2,

'center_y': (wy1 + wy2) // 2

}

nearby_ppe = []

for ppe in ppe_items:

px1 = ppe['bbox_xyxy']['x1']

py1 = ppe['bbox_xyxy']['y1']

px2 = ppe['bbox_xyxy']['x2']

py2 = ppe['bbox_xyxy']['y2']

if px1 >= wx1 - 50 and px2 <= wx2 + 50 and py1 >= wy1 - 50 and py2 <= wy2 + 50:

nearby_ppe.append(ppe['class_name'])

if nearby_ppe:

compliance_analysis['workers_with_ppe'] += 1

else:

compliance_analysis['workers_without_ppe'] += 1

compliance_analysis['non_compliant_workers'].append({

'worker_bbox': worker_region,

'confidence': worker['confidence'],

'missing_ppe': ppe_classes.get('worker', [])

})

logger.info(f"Compliance: {compliance_analysis['workers_with_ppe']}/{len(workers)} workers have PPE")

return compliance_analysis

def check_hazard_zone_violation(detections: Dict, hazard_zones: List[Dict]) -> Dict:

violations = {

'image_path': detections['image_path'],

'violations': []

}

workers = [d for d in detections['detections'] if d['class_name'] == 'worker']

for worker in workers:

wx1 = worker['bbox_xyxy']['x1']

wy1 = worker['bbox_xyxy']['y1']

wx2 = worker['bbox_xyxy']['x2']

wy2 = worker['bbox_xyxy']['y2']

worker_center_x = (wx1 + wx2) / 2

worker_center_y = (wy1 + wy2) / 2

for zone in hazard_zones:

if (zone['x1'] <= worker_center_x <= zone['x2'] and

zone['y1'] <= worker_center_y <= zone['y2']):

violations['violations'].append({

'worker_bbox': {

'x1': wx1, 'y1': wy1, 'x2': wx2, 'y2': wy2

},

'worker_confidence': worker['confidence'],

'hazard_zone': zone['name'],

'severity': zone.get('severity', 'medium'),

'worker_position': {

'center_x': int(worker_center_x),

'center_y': int(worker_center_y)

}

})

if violations['violations']:

logger.warning(f"Found {len(violations['violations'])} hazard zone violations")

return violations

class WorkerTracker:

def __init__(self, max_distance: float = 50.0):

self.max_distance = max_distance

self.tracked_workers = {}

self.next_id = 0

def update(self, detections: Dict, frame_id: int) -> Dict:

workers = [d for d in detections['detections'] if d['class_name'] == 'worker']

new_centroids = []

for worker in workers:

cx = (worker['bbox_xyxy']['x1'] + worker['bbox_xyxy']['x2']) / 2

cy = (worker['bbox_xyxy']['y1'] + worker['bbox_xyxy']['y2']) / 2

new_centroids.append({'x': cx, 'y': cy, 'detection': worker})

updated_detections = detections.copy()

updated_detections['detections'] = []

matched_ids = set()

for new_centroid in new_centroids:

best_match_id = None

best_distance = self.max_distance

for worker_id, track_data in self.tracked_workers.items():

if worker_id in matched_ids:

continue

last_pos = track_data['positions'][-1]

distance = np.sqrt(

(new_centroid['x'] - last_pos['x'])**2 +

(new_centroid['y'] - last_pos['y'])**2

)

if distance < best_distance:

best_distance = distance

best_match_id = worker_id

if best_match_id is not None:

track_id = best_match_id

matched_ids.add(track_id)

else:

track_id = self.next_id

self.next_id += 1

self.tracked_workers[track_id] = {'positions': [], 'frames': []}

self.tracked_workers[track_id]['positions'].append({

'x': new_centroid['x'],

'y': new_centroid['y'],

'frame': frame_id

})

self.tracked_workers[track_id]['frames'].append(frame_id)

new_detection = new_centroid['detection'].copy()

new_detection['track_id'] = track_id

updated_detections['detections'].append(new_detection)

return updated_detections

def get_dwell_time(self, worker_id: int, fps: int = 30) -> float:

if worker_id not in self.tracked_workers:

return 0.0

frames = self.tracked_workers[worker_id]['frames']

dwell_frames = len(frames)

dwell_time = dwell_frames / fps

return dwell_time